import { Quote, quote as actual } from "iexcloud_api_wrapper"

const mockQuote: Quote = {
  symbol: "",
  companyName: "Name",
  open: 10,
  openTime: 10,
  close: 10,
  closeTime: 10,
  high: 10,
  low: 10,
  latestPrice: 10,
  latestUpdate: 10,
  latestVolume: 10,
  iexRealtimePrice: 10,
  iexRealtimeSize: 10,
  iexLastUpdated: 10,
  delayedPrice: 10,
  delayedPriceTime: 10,
  extendedPrice: 10,
  extendedChange: 10,
  extendedChangePercent: 10,
  extendedPriceTime: 10,
  previousClose: 10,
  change: 10,
  changePercent: 10,
  iexMarketPercent: 10,
  iexVolume: 10,
  avgTotalVolume: 10,
  iexBidPrice: 10,
  iexBidSize: 10,
  iexAskPrice: 10,
  iexAskSize: 10,
  marketCap: 10,
  week52High: 10,
  week52Low: 10,
  ytdChange: 10,
  calculationPrice: "10",
  latestSource: "latestSource",
  latestTime: "latestTime",
}

export const quote: typeof actual = (symbol) =>
  Promise.resolve({ ...mockQuote, symbol })
