apiVersion: v1
kind: Service
metadata:
  name: insights-client
  labels:
    app: insights-client
spec:
  selector:
    app: insights-client
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: http
  - name: apollo
    port: 4000
    targetPort: apollo
  type: LoadBalancer
  loadBalancerIP: 35.195.236.145
