apiVersion: v1
kind: Service
metadata:
  name: insights
  labels:
    app: insights
spec:
  selector:
    app: insights
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  type: LoadBalancer
  loadBalancerIP: __EXTERNAL_IP__
