export { colors } from './colors'
export type { Color } from './colors'
export { default as GlobalStyle } from './globals'
export { ThemeConsumer, ThemeName, ThemeProvider, useTheme } from './ThemeContext'
export { getColor, themes } from './themes'
export type { Theme } from './themes'
